# Generated by Django 6.0.5 on 2026-05-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='date_hired',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACTUAL', 'Contractual')], default='New', max_length=25),
        ),
    ]
