# Generated by Django 6.0.5 on 2026-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employees_date_hired_employees_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='on_leave',
            field=models.BooleanField(default=False),
        ),
    ]
