# Generated by Django 6.0.5 on 2026-05-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employees_on_leave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employees',
        ),
    ]
