# Generated by Django 6.0.5 on 2026-05-08 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0004_delete_employees'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=50)),
                ('address', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('RFID', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=50)),
                ('basic_pay', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACTUAL', 'Contractual')], default='New', max_length=25)),
                ('date_hired', models.DateField(auto_now=True)),
                ('on_leave', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
