# Generated by Django 6.0.5 on 2026-05-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
