# Generated by Django 6.0.5 on 2026-05-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employees_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='employee_id',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
