# Generated by Django 6.0.5 on 2026-05-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employees_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='RFID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
