# Generated by Django 6.0.5 on 2026-05-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_alter_employees_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
