# Generated by Django 6.0.5 on 2026-05-10 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employees_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='basic_pay',
            field=models.IntegerField(max_length=10),
        ),
    ]
