# Generated by Django 6.0.5 on 2026-05-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_alter_employees_basic_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='basic_pay',
            field=models.IntegerField(),
        ),
    ]
