# Generated by Django 6.0.5 on 2026-06-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_alter_employees_basic_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='basic_pay',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='employees',
            name='date_hired',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(choices=[('PERMANENT', 'Permanent'), ('CONTRACTUAL', 'Contractual')], default='PERMANENT', max_length=25),
        ),
    ]
