# Generated by Django 6.0.5 on 2026-06-05 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_alter_employees_basic_pay_alter_employees_date_hired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='duty_in',
            field=models.TimeField(default=datetime.time(7, 0)),
        ),
        migrations.AddField(
            model_name='employees',
            name='duty_out',
            field=models.TimeField(default=datetime.time(5, 0)),
        ),
    ]
