# Generated by Django 6.0.5 on 2026-06-07 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_employees_duty_in_employees_duty_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
