# Generated by Django 6.0.5 on 2026-05-13 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_alter_employees_basic_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('VACATION', 'Vacation'), ('EMERGENCY', 'Emergency'), ('MATERNITY', 'Maternity/Paternity')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sick_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vacation_leave', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('SPL', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='employees.employees')),
            ],
        ),
    ]
