# Generated by Django 6.0.5 on 2026-05-15 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEAVES', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
