# Generated by Django 6.0.5 on 2026-05-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEAVES', '0003_leavehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavehistory',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
