# Generated by Django 6.0.5 on 2026-06-19 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LEAVES', '0004_leavehistory_duration'),
        ('employees', '0014_employees_is_archive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaverequest',
            name='SPL',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='sick_leave',
        ),
        migrations.RemoveField(
            model_name='leaverequest',
            name='vacation_leave',
        ),
        migrations.AlterField(
            model_name='leavehistory',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_history', to='employees.employees'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('VACATION', 'Vacation Leave'), ('SICK', 'Sick Leave'), ('SPL', 'Special Privilege Leave'), ('SOLO_PARENT', 'Solo Parent Leave'), ('MATERNITY', 'Maternity Leave'), ('PATERNITY', 'Paternity Leave')], max_length=20),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('sick', models.DecimalField(decimal_places=2, default=15, max_digits=5)),
                ('spl', models.DecimalField(decimal_places=2, default=3, max_digits=5)),
                ('solo_parent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('maternity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('paternity', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance', to='employees.employees')),
            ],
        ),
    ]
