# Generated by Django 6.0.5 on 2026-05-08 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0009_alter_employees_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_worked', models.IntegerField(default=0)),
                ('absent_days', models.IntegerField(default=0)),
                ('late_minutes', models.IntegerField(default=0)),
                ('leave_days', models.IntegerField(default=0)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('first_period_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('second_period_pay', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('SSS_SALARY', 'SSS Salary Loan'), ('SSS_MPL', 'SSS MPL'), ('SSS_CALAMITY', 'SSS Calamity'), ('SSS_EDUC', 'SSS Education'), ('PAGIBIG_HOUSING', 'Pag-IBIG Housing'), ('PAGIBIG_MPL', 'Pag-IBIG MPL'), ('COOP', 'Coop Loan')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod')),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sss_personal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sss_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sss_ec', models.DecimalField(decimal_places=2, default=30, max_digits=10)),
                ('pagibig_personal', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('pagibig_employer', models.DecimalField(decimal_places=2, default=200, max_digits=10)),
                ('philhealth_personal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('philhealth_employer', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('coop_share', models.DecimalField(decimal_places=2, default=300, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employees')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrollperiod')),
            ],
        ),
    ]
