# Generated by Django 6.0.5 on 2026-05-10 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0011_alter_employees_basic_pay'),
    ]

    operations = [
        migrations.CreateModel(
            name='loans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSS_salary', models.IntegerField()),
                ('SSS_calamity', models.IntegerField()),
                ('SSS_MPL', models.IntegerField()),
                ('PAGIBIG_MPL', models.IntegerField()),
                ('PAGIBIG_housing', models.IntegerField()),
                ('COOP', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='employees.employees')),
            ],
        ),
    ]
