# Generated by Django 6.0.5 on 2026-05-10 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOANS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='SSS_educ',
            field=models.IntegerField(null=True),
        ),
    ]
