# Generated by Django 6.0.5 on 2026-05-11 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOANS', '0002_loans_sss_educ'),
        ('employees', '0011_alter_employees_basic_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_loans', to='employees.employees'),
        ),
    ]
