# Generated by Django 6.0.5 on 2026-05-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOANS', '0003_alter_loans_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loans',
            name='COOP',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='PAGIBIG_MPL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='PAGIBIG_housing',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='SSS_MPL',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='SSS_calamity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='SSS_educ',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loans',
            name='SSS_salary',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
