# Generated by Django 6.0.5 on 2026-05-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOANS', '0004_alter_loans_coop_alter_loans_pagibig_mpl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='COOP_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='PAGIBIG_MPL_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='PAGIBIG_housing_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='SSS_MPL_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='SSS_calamity_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='SSS_educ_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loans',
            name='SSS_salary_monthly',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
