# Generated by Django 6.0.5 on 2026-05-13 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOANS', '0005_loans_coop_monthly_loans_pagibig_mpl_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='total_loans',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
