# Generated by Django 6.0.5 on 2026-05-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LOANS', '0007_alter_loans_coop_alter_loans_coop_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='total_deductions',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
