# Generated by Django 6.0.5 on 2026-05-13 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LOANS', '0008_loans_total_deductions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loans',
            old_name='total_deductions',
            new_name='monthly_deductions',
        ),
    ]
