# Generated by Django 6.0.5 on 2026-06-21 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('EMPLOYEE_CREATED', 'Employee Created'), ('EMPLOYEE_EDITED', 'Employee Edited'), ('EMPLOYEE_ARCHIVED', 'Employee Archived'), ('SALARY_CHANGED', 'Salary Changed'), ('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('LEAVE_FILED', 'Leave Filed'), ('LEAVE_CREDITED', 'Leave Credited'), ('PASSWORD_RESET', 'Password Reset'), ('PASSWORD_CHANGED', 'Password Changed'), ('PAYROLL_LOCKED', 'Payroll Locked'), ('LOAN_UPDATED', 'Loan Updated'), ('ADJUSTMENT_ADDED', 'Adjustment Added')], max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
